.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. materia_qt test_materia_qt
clean: FORCE
	$(MAKE) -C .. materia_qt_clean test_materia_qt_clean
check: FORCE
	$(MAKE) -C .. test_materia_qt_check
materia-qt materia-qt.exe: FORCE
	 $(MAKE) -C .. materia_qt
